# Generated by Django 6.0.4 on 2026-04-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('title_guidance', models.CharField(blank=True, max_length=255)),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('audience', models.CharField(blank=True, max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('writing_style', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('desired_length', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='blogs.blogproject')),
            ],
        ),
    ]
