# Generated by Django 6.0.4 on 2026-04-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.JSONField(blank=True, default=list)),
                ('canonical_url', models.URLField(blank=True)),
                ('schema_markup', models.JSONField(blank=True, default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='blogs.blogproject')),
            ],
        ),
    ]
